# Generated by Django 6.0.4 on 2026-04-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_homework_user_alter_note_user_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('study', 'Study'), ('health', 'Health'), ('other', 'Other')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
    ]
