# Generated by Django 6.0.4 on 2026-04-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_todo_category_todo_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='pronunciation',
            field=models.CharField(blank=True, help_text='Pronunciation guide, e.g., /ˈwɜːrd/', max_length=200),
        ),
    ]
